spring:
  servlet:
    multipart:
      location: /Users/kimnayeon/Documents/fileupload
      max-file-size: 100MB
      max-request-size: 300MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
