spring:
  profiles:
    include: mariadb
  servlet:
    multipart:
      location: /Users/kimnayeon/Documents/fileupload
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
